site_name: Switchless docs
theme:
    name: null
    custom_dir: 'docs/custom_theme2/'
    sidebars: 
        - about
        - search
extra:
    logo: files/asyncauto-handbook-logo.png
    sidebars:
        - about
        - navigation
    homepage_sidebars:
        - about
        - navigation

nav:
    - Milestones: milestones.md
    - Philosophies: 
        - Document First Approach: philosophies/document_first_approach.md

plugins:
    - search
    # - encryptcontent:
        # global_password: 'your_password'

markdown_extensions:
  - toc:
      permalink: true
