site_name: Asyncauto handboook
site_dir: public
theme:
    name: null
    custom_dir: 'docs/custom_theme2/'
    sidebars: 
        - about
        - search
extra:
    logo: files/asyncauto-handbook-logo.png
    sidebars:
        - about
        - navigation
    homepage_sidebars:
        - about
        - navigation

nav:
    - Milestones: milestones.md
    - Philosophies: 
        - Document First Approach: philosophies/document_first_approach.md
        - Premature Optimisation: philosophies/premature_optimisation.md
        - Build what you are sure of: philosophies/build_what_you_are_sure_of.md
        - Iteration: philosophies/iteration.md
        - Do not over apply any guideline: philosophies/do_not_over_apply_any_guideline.md
        - Wasting some work: philosophies/wasting_some_work.md
        - All advice sum up to zero: philosophies/all_advice_sum_up_to_zero.md
    - Roles: 
        - Introduction: roles/introduction.md
        - Front-end Developer Manual: roles/frontend_developer.md
    - Recommended readings: recommended_readings.md

plugins:
    - search
    # - encryptcontent:
        # global_password: 'your_password'

markdown_extensions:
  - toc:
      permalink: true
